apiVersion: apps/v1
kind: Deployment
metadata:
  # name of deployment
  name: exec-sdc
spec:
  # 3 instances of SDC
  replicas: 3
  selector:
    matchLabels:
      app: exec-sdc
  template:
    metadata:
      labels:
        app : exec-sdc
    spec:
      containers:
      - name : exec-sdc
        # pull sdc-dpm docker image which is present in gcp container registry
        image: streamsets/datacollector:3.20.0
        imagePullPolicy: Always
        ports:
        - containerPort: 18360
        lifecycle:
          preStop:
            exec:
              command: ["/tmp/pre-stop.sh"]
        volumeMounts:
        - mountPath: "/var/lib/sdc-resources"
          name : secret-volume
          readOnly : true
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PORT0
          value: "18630"
        - name: ORG
          value: "your_org"
        - name: URL
          value: "https://cloud.streamsets.com"
        - name: LABELS
          value: "k8s-exec-sdc"
      volumes:
      - name : secret-volume
        secret :
          secretName : mysecrets
